const ItemsActionTypes = {
  GET_ITEMS_START: 'GET_ITEMS_START',
  GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS',
  GET_ITEMS_FAILURE: 'GET_ITEMS_FAILURE',
  GET_ITEM_START: 'GET_ITEM_START',
  GET_ITEM_SUCCESS: 'GET_ITEM_SUCCESS',
  GET_ITEM_FAILURE: 'GET_ITEM_FAILURE',
};

export default ItemsActionTypes;